### ISSUE TITLE
When the results are public between competitors

### ISSUE THREAD

**Issue by honghanhh** [ai-systems/tg2022task_premise_retrieval#1]
When the results are public between competitors?
Thanks in advance.

**Comment by mValentino91** [comment]
Hi, we just invited participants to make their results public on the leaderboard. These should appear at the following link: https://codalab.lisn.upsaclay.fr/competitions/5692#results.

**Comment by mValentino91** [comment]
If you are a participant you can make your results public here: https://codalab.lisn.upsaclay.fr/competitions/5692#participate-submit_results

**Comment by honghanhh** [comment]
Hi @mValentino91, I joined the competition but I only saw mine (internal) and results from Mr.mvalentino on the leaderboard.
The link above indicates:
"This phase has not started yet. The leaderboard is still hidden to participants but visible to organizers"
Thanks in advance.

**Comment by mValentino91** [comment]
Hi, if you click on "Evaluation" (green button) you should be able to see your submissions and decide which one to submit to the leaderboard. At the moment we are still waiting for participants to make their submissions public. Please let me know if there are any issues doing that. Thank you!

**Comment by honghanhh** [comment]
Thank you.

**Comment by mValentino91** [comment]
You are welcome! We will send additional details about the competition soon! Thank you for taking part!

**Comment by honghanhh** [comment]
Is this eligible to submit the system description for the shared tasks but the methodologies are not related to graph? Thanks.

**Comment by mValentino91** [comment]
Hi, absolutely. The solution shouldn't necessarily involve graphs. We will provide additional info for the submission of description papers soon!

**Comment by honghanhh** [comment]
As the deadline on the website is mentioned today, so I just wanna make sure before submitting.
If the additional info for the submission of description papers  will be announced later, does it mean the deadline extend?
Thanks.

**Comment by mValentino91** [comment]
Hi, we just extended the deadline. Thanks!
